name: Check Transcrypt
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
jobs:
  setup-transcrypt:
    uses: ./.github/workflows/setup-transcrypt.yml
  CheckTranscrypt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name: Decrypt
        run: |
          cd ./main
          ls -l
          transcrypt -y -p $TRANSCRYPT_PASSPHRASE
        env:
          TRANSCRYPT_PASSPHRASE: ${{ secrets.TRANSCRYPT_PASSPHRASE }}
      - name: Show encrypted file
        run: |
          cd ./main
          tail key.json
      


      
