name: Check Transcrypt
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
jobs:
  CheckTranscrypt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout Transcrypt
        uses: actions/checkout@v3
        with:
          repository: elasticdog/transcrypt
          path: transcrypt
      - name: Install Transcrypt
        run: |
          cd ./transcrypt
          ln -s ${PWD}/transcrypt /usr/local/bin/transcrypt
      - name: Decrypt
        run: |
          cd ./main
          ls -l
          transcrypt -y -p $TRANSCRYPT_PASSPHRASE
        env:
          TRANSCRYPT_PASSPHRASE: ${{ secrets.TRANSCRYPT_PASSPHRASE }}
      - name: Show encrypted file
        run: tail "$ASC_API_KEYS_PATH/key.json"
        env:
          ASC_API_KEYS_PATH: '${{ github.wokspace }}/main/keys'
      


      
