name: Check Transcrypt
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
jobs:
  CheckTranscrypt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2 # The Publish API docs step compares against one commit earlier
      - name: install transcrypt
        working-directory: tools
        run: |
          git clone https://github.com/elasticdog/transcrypt.git
          cd transcrypt/
          ln -s ${PWD}/transcrypt /usr/local/bin/transcrypt
      - name: Decrypt
        run: |
          ls -l
          transcrypt -y -p $TRANSCRYPT_PASSPHRASE
        env:
          TRANSCRYPT_PASSPHRASE: ${{ secrets.TRANSCRYPT_PASSPHRASE }}
      - name: Show encrypted file
        run: tail key.json
      


      
