name: Setup Transcrypt
on:
  workflow_call:
jobs:
  setup-transcrypt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: elasticdog/transcrypt
          path: transcrypt
      - name: Create shortcut
        run: |
          cd ./transcrypt
          ln -s ${PWD}/transcrypt /usr/local/bin/transcrypt